/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   code-mirror-hint-container.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

export {CodeMirrorHintContainer};

/**
 * `code-mirror-hint-container`
 * UI element for hint display.
 */
declare class CodeMirrorHintContainer extends PolymerElement {
}

declare global {

  interface HTMLElementTagNameMap {
    "code-mirror-hint-container": CodeMirrorHintContainer;
  }
}
